#默认使用配置
spring:
  application:
    name: price-api
  mvc:
    static-path-pattern: /**


###服务启动端口号
server:
  port: 8002

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
  instance:
    appname: fegin-api-service
    virtual-host-name: fegin-api-service
    secure-virtual-host-name: fegin-api-service
